# Task 3 : NumPy Functions and Operations

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[9,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a.size

6

In [5]:
a.dtype

dtype('int64')

In [6]:
a.ndim

2

In [7]:
np.zeros((2, 2)) 

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones((3, 3))  

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.full((4,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [10]:
np.eye(3)           

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
np.sort(a)

array([[1, 2, 3],
       [5, 6, 9]])

In [14]:
a.reshape((3,2))

array([[1, 2],
       [3, 9],
       [5, 6]])

In [15]:
a.flatten()

array([1, 2, 3, 9, 5, 6])

In [16]:
b = a.copy()
print(b)

[[1 2 3]
 [9 5 6]]


In [17]:
print(a+2)

[[ 3  4  5]
 [11  7  8]]


In [18]:
unique = np.unique(a)
print(unique)

[1 2 3 5 6 9]


In [19]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
emp = np.empty((3,4))
print(emp)

[[9.35027920e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.39733969e-066 3.11170566e-032 2.09164746e-076]
 [3.56777230e-057 2.69768796e+184 5.39967677e-066 5.19824243e-062]]


In [21]:
rdm = np.random.rand(3,3)
print(rdm)

[[0.38164926 0.10695019 0.31131957]
 [0.008857   0.75450724 0.93006364]
 [0.81559071 0.92620743 0.94376884]]


In [22]:
ide = np.identity(6)
print(ide)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [23]:
a.sum(axis=0)

array([10,  7,  9])

In [24]:
a.sum( axis=1)

array([ 6, 20])

In [25]:
arr = np.array([1,2,5,4,7,3,8,7,6,9])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.reshape(5,2)

array([[1, 2],
       [5, 4],
       [7, 3],
       [8, 7],
       [6, 9]])

In [29]:
arr.ravel()

array([1, 2, 5, 4, 7, 3, 8, 7, 6, 9])

In [30]:
arr.sum()

np.int64(52)

In [31]:
arr2 = np.array([4,9,16,25,36])
np.sqrt(arr2)

array([2., 3., 4., 5., 6.])

In [34]:
np.where(arr > 3)

(array([2, 3, 4, 6, 7, 8, 9]),)